#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
#nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy |& /usr/bin/logshifter -tag diy &
export HTTP_CLIENT="wget --no-check-certificate -O"
export PORT=$OPENSHIFT_DIY_PORT
#export HOST=$OPENSHIFT_DIY_IP
export HOME=$OPENSHIFT_DATA_DIR
export LEIN_JVM_OPTS=-Duser.home=$HOME
cd $OPENSHIFT_REPO_DIR
export JAVA_OPTS="-server -XX:PermSize=32M -XX:MaxPermSize=32m -Xms256m -Xmx256m -XX:NewRatio=1 -XX:SurvivorRatio=32"
nohup $OPENSHIFT_REPO_DIR/bin/lein ring server-headless $PORT 2>&1 | /usr/bin/logshifter -tag diy &
#nohup $OPENSHIFT_REPO_DIR/bin/lein trampoline run 2>&1 | /usr/bin/logshifter -tag diy &
