#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
#nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy |& /usr/bin/logshifter -tag diy &
export PROJECTS="adapter-csv adapter-db adapter-hl7v2"
export HTTP_CLIENT="wget --no-check-certificate -O"
export PORT=$OPENSHIFT_DIY_PORT
#export HOST=$OPENSHIFT_DIY_IP
export HOME=$OPENSHIFT_DATA_DIR
export LEIN_JVM_OPTS=-Duser.home=$HOME
export LEIN=$OPENSHIFT_REPO_DIR/bin/lein
cd $OPENSHIFT_REPO_DIR
for dep in $PROJECTS;
do
  cd $dep
  pwd
  $LEIN clean; $LEIN deps; $LEIN install
  cd ..
done
cd webui
echo "$(pwd) clean..."
$LEIN clean; $LEIN deps
#export JAVA_OPTS="-server -XX:PermSize=32M -XX:MaxPermSize=32m -Xms256m -Xmx256m -XX:NewRatio=1 -XX:SurvivorRatio=32"
$LEIN ring server-headless $PORT 2>&1
#nohup $OPENSHIFT_REPO_DIR/bin/lein ring server-headless $PORT 2>&1 | /usr/bin/logshifter -tag diy &
