language: clojure
install: "./build.sh"
deploy:
  provider: openshift
  user: celisdelafuente@gmail.com
  password:
    secure: hiK+oaG+bDQAE4DhkeMiiNL2a3Mniln4DvkIYQwoRWApbJhfNb3ozwvs85L7SYj2Ep4m8vxyusZ+BRDsejxHU0QR3yflfRohtA7iysRdSBPtQXctnjK0h1bbvwC0Knsy2Sy3QLAgeOgjQo93y4bhkCxTfqhyUKC2VggwFACnFEJXuxr+nleBuVa/+f7vAFPSCdigKxCkh1jrhqUd8Mbs8OTtTjMH6bm++uY5PkUtVYKmvO//CflVynOZI50x7SxkvKsqRyW5ujKOnksFTubZS63RuUr2E8ZPe5mG5bTwRZzX+RY7yX1KUbXxTvFCI7Wuxgcvi1ZL9o+OGa84PtX22rVZ5GUCQMcnixHzJXpL1TwhD0aRGY4uWDLNkB/IaUN+0pjkLtlnR814zJHccwut+Bwiu+S8RjDMrp/EanLcyzmI161T3RqPjBde4wl6C4cIZ2yol5QEhMa1+x/7a+GkXLONnH9S6WGncBtG9ISQmV9BjaJa8FW6r7hB/V/4ZhYLIVa9405O1xZdTR8Ez1/kw24IV3FZ6ndecAiEGkSyuKboDlV+xSzwl/y2d26a9X5Ix7GJoaGkcAIOIBg32aQMIjf0xcCMXVLj6pdsR+1IfMwO7hKxGlC20D8+D4X1/gjDmBKVRQ1451X4v1maiFjNF0bJtqLsjY/2jlYsyawqbNI=
  app: iridescence
  domain: valhala
  on:
    repo: ecelis/iridescence
