/*
 * Generated by XDoclet - Do not edit!
 */
package org.compiere.interfaces;

import javax.ejb.Local;

/**
 * Local interface for compiere/Server.
 */
@Local
public interface ServerLocal extends Server{
}
