/*
 * Generated by XDoclet - Do not edit!
 */
package org.compiere.interfaces;

import javax.ejb.Local;

/**
 * Local interface for compiere/Status.
 */
@Local
public interface StatusLocal extends Status {
}
