/******************************************************************************
 * (C) eCareSoft, LLC.                                                        *
 ******************************************************************************/
package org.compiere.model;

import java.math.BigDecimal;
import org.compiere.util.KeyNamePair;

/** Generated Interface for EXME_Area
 *  @author Generated Class 
 *  @version Release 1.1.2
 */
public interface I_EXME_Area 
{

    /** TableName=EXME_Area */
    public static final String Table_Name = "EXME_Area";

    /** AD_Table_ID=1000028 */
    public static final int Table_ID = MTable.getTable_ID(Table_Name);

    KeyNamePair Model = new KeyNamePair(Table_ID, Table_Name);

    /** AccessLevel = 1 - Org 
     */
    BigDecimal accessLevel = BigDecimal.valueOf(1);

    /** Load Meta Data */

    /** Column name AD_Org_ID */
    public static final String COLUMNNAME_AD_Org_ID = "AD_Org_ID";

	/** Set Organization.
	  * Organizational entity within client
	  */
	public void setAD_Org_ID (int AD_Org_ID);

	/** Get Organization.
	  * Organizational entity within client
	  */
	public int getAD_Org_ID();

    /** Column name ConEquipos */
    public static final String COLUMNNAME_ConEquipos = "ConEquipos";

	/** Set Medical equipment do you have?.
	  * Medical equipment do you have?
	  */
	public void setConEquipos (boolean ConEquipos);

	/** Get Medical equipment do you have?.
	  * Medical equipment do you have?
	  */
	public boolean isConEquipos();

    /** Column name Description */
    public static final String COLUMNNAME_Description = "Description";

	/** Set Description.
	  * Optional short description of the record
	  */
	public void setDescription (String Description);

	/** Get Description.
	  * Optional short description of the record
	  */
	public String getDescription();

    /** Column name EXME_Area_ID */
    public static final String COLUMNNAME_EXME_Area_ID = "EXME_Area_ID";

	/** Set Service.
	  * Service
	  */
	public void setEXME_Area_ID (int EXME_Area_ID);

	/** Get Service.
	  * Service
	  */
	public int getEXME_Area_ID();

    /** Column name EXME_FacTypeCode_ID */
    public static final String COLUMNNAME_EXME_FacTypeCode_ID = "EXME_FacTypeCode_ID";

	/** Set Fac. Type Code.
	  * Fac. Type Code
	  */
	public void setEXME_FacTypeCode_ID (int EXME_FacTypeCode_ID);

	/** Get Fac. Type Code.
	  * Fac. Type Code
	  */
	public int getEXME_FacTypeCode_ID();

	public I_EXME_FacTypeCode getEXME_FacTypeCode() throws RuntimeException;

    /** Column name EXME_Frequency1_ID */
    public static final String COLUMNNAME_EXME_Frequency1_ID = "EXME_Frequency1_ID";

	/** Set Frequency 1.
	  * Frequency Header ID
	  */
	public void setEXME_Frequency1_ID (int EXME_Frequency1_ID);

	/** Get Frequency 1.
	  * Frequency Header ID
	  */
	public int getEXME_Frequency1_ID();

	public I_EXME_Frequency1 getEXME_Frequency1() throws RuntimeException;

    /** Column name EXME_Frequency2_ID */
    public static final String COLUMNNAME_EXME_Frequency2_ID = "EXME_Frequency2_ID";

	/** Set Frequency 2.
	  * Frequency First Detail ID
	  */
	public void setEXME_Frequency2_ID (int EXME_Frequency2_ID);

	/** Get Frequency 2.
	  * Frequency First Detail ID
	  */
	public int getEXME_Frequency2_ID();

	public I_EXME_Frequency2 getEXME_Frequency2() throws RuntimeException;

    /** Column name IsAutoGenerated */
    public static final String COLUMNNAME_IsAutoGenerated = "IsAutoGenerated";

	/** Set Auto Generated 	  */
	public void setIsAutoGenerated (boolean IsAutoGenerated);

	/** Get Auto Generated 	  */
	public boolean isAutoGenerated();

    /** Column name IsTemplate */
    public static final String COLUMNNAME_IsTemplate = "IsTemplate";

	/** Set Is Template	  */
	public void setIsTemplate (boolean IsTemplate);

	/** Get Is Template	  */
	public boolean isTemplate();

    /** Column name Name */
    public static final String COLUMNNAME_Name = "Name";

	/** Set Name.
	  * Alphanumeric identifier of the entity
	  */
	public void setName (String Name);

	/** Get Name.
	  * Alphanumeric identifier of the entity
	  */
	public String getName();

    /** Column name TipoArea */
    public static final String COLUMNNAME_TipoArea = "TipoArea";

	/** Set Area Type.
	  * Admission Area Type
	  */
	public void setTipoArea (String TipoArea);

	/** Get Area Type.
	  * Admission Area Type
	  */
	public String getTipoArea();

    /** Column name Value */
    public static final String COLUMNNAME_Value = "Value";

	/** Set Search Key.
	  * Search key for the record in the format required - must be unique
	  */
	public void setValue (String Value);

	/** Get Search Key.
	  * Search key for the record in the format required - must be unique
	  */
	public String getValue();
}
